### ISSUE TITLE
Infrastructure of the project

### ISSUE THREAD

**Issue by DigitalSmile** [maxtomin/decimal#1]
Hi! Thanks for a great library!
Are there any plans for gradle and pushing artifact into maven repo?

**Comment by DigitalSmile** [comment]
Since I have no answer, I decided to fork it into separate account for Maven Repo deployment and to have a chance to extend the library -> https://github.com/quickdecimal/decimal
@maxtomin I have invited you to participate in the new repo as an owner. Feel free to contact me if you have any questions.

**Comment by maxtomin** [comment]
Hi,

Sorry for delay. I can’t spend much time on this project in the next half-year, but I’m interested in the future  improvements.

Feel free to fork and modify.

Max
